package examen3;
import java.sql.*;
import javax.swing.JOptionPane;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import com.itextpdf.text.PageSize;
import java.awt.HeadlessException;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;

public class InterfazBiblio extends javax.swing.JFrame {

    /**
     * Creates new form InterfazBiblio
     */
    public InterfazBiblio() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Nombre = new javax.swing.JTextField();
        Autor = new javax.swing.JTextField();
        Año = new javax.swing.JTextField();
        Editorial = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Estado = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        Mantenimiento = new javax.swing.JTextField();
        Id = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        BuscaId = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        label_status = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("Nombre");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 60, 80, 14);

        jLabel4.setText("Autor");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 140, 90, 14);
        getContentPane().add(Nombre);
        Nombre.setBounds(10, 80, 300, 20);
        getContentPane().add(Autor);
        Autor.setBounds(10, 160, 301, 20);
        getContentPane().add(Año);
        Año.setBounds(10, 120, 300, 20);
        getContentPane().add(Editorial);
        Editorial.setBounds(10, 200, 301, 20);

        jLabel6.setText("Editorial");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(10, 180, 90, 14);

        jLabel2.setText("Año");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 100, 70, 14);

        jLabel7.setText("Estado");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(10, 220, 100, 14);
        getContentPane().add(Estado);
        Estado.setBounds(10, 240, 300, 20);

        jLabel8.setText("Mantenimiento");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(10, 260, 130, 14);
        getContentPane().add(Mantenimiento);
        Mantenimiento.setBounds(10, 280, 301, 20);
        getContentPane().add(Id);
        Id.setBounds(10, 36, 80, 20);

        jLabel5.setText("Id");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 16, 10, 14);

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Registrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(10, 320, 93, 23);

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Modificar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(110, 320, 93, 23);

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Eliminar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(210, 320, 93, 23);

        jButton5.setBackground(new java.awt.Color(0, 0, 0));
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Generar PDF");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(310, 320, 110, 23);

        jLabel3.setText("Codigo del Libro");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 360, 130, 14);
        getContentPane().add(BuscaId);
        BuscaId.setBounds(10, 380, 100, 20);

        jButton4.setBackground(new java.awt.Color(0, 0, 0));
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Buscar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(120, 380, 65, 23);

        label_status.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(label_status);
        label_status.setBounds(390, 440, 0, 0);

        fondo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/Banner.jpg"))); // NOI18N
        fondo.setAlignmentX(1.0F);
        fondo.setAlignmentY(1.0F);
        getContentPane().add(fondo);
        fondo.setBounds(190, -50, 220, 120);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        try {
            Connection cn = DriverManager.getConnection("jdbc:mariadb://localhost:3305/Librerias", "root", "1234");
            PreparedStatement pst = cn.prepareStatement("insert into Libreria (Nombre,Estado,Año,Autor,Editorial,ID,Mantenimiento) values(?,?,?,?,?,?,?)");

            pst.setString(1, Nombre.getText());
            pst.setString(2, Estado.getText());
            pst.setString(3, Año.getText());
            pst.setString(4, Autor.getText());
            pst.setString(5, Editorial.getText());
            pst.setString(6, Id.getText());
            pst.setString(7, Mantenimiento.getText());
            pst.executeUpdate();

            Nombre.setText("");
            Año.setText("");
            Estado.setText("");
            Año.setText("");
            Mantenimiento.setText("");
            Id.setText("");
            Editorial.setText("");
            Autor.setText("");
            label_status.setText("Registro exitoso.");
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        try {
            String ID = BuscaId.getText().trim();

            Connection cn = DriverManager.getConnection("jdbc:mariadb://localhost:3305/Librerias", "root", "1234");
            PreparedStatement pst = cn.prepareStatement("update Libreria set Nombre = ?, Estado = ?,Año = ?,Autor = ?,Editorial= ?,Id = ?,Mantenimiento = ? where ID = " + ID);

            pst.setString(1, Nombre.getText().trim());
            pst.setString(2, Estado.getText().trim());
            pst.setString(3, Año.getText().trim());
            pst.setString(4, Autor.getText().trim());
            pst.setString(5, Editorial.getText());
            pst.setString(6, Id.getText());
            pst.setString(7, Mantenimiento.getText());
            pst.executeUpdate();

            label_status.setText("Modificación de la informacion realizada con exito.");

        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        try {
            Connection cn = DriverManager.getConnection("jdbc:mariadb://localhost:3305/Librerias", "root", "1234");
            PreparedStatement pst = cn.prepareStatement("delete from Libreria where ID = ?");

            pst.setString(1, BuscaId.getText().trim());
            pst.executeUpdate();

            Nombre.setText("");
            Año.setText("");
            BuscaId.setText("");
            Estado.setText("");
            Año.setText("");
            Editorial.setText("");
            Autor.setText("");
            Id.setText("");

            label_status.setText("Libro eliminado.");

        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        Document documento = new Document(PageSize._11X17);
        try {
            String ruta = System.getProperty("user.home");
            PdfWriter.getInstance(documento, new FileOutputStream(ruta + "/Desktop/LibroInfo.pdf"));
            documento.open();
            documento.addTitle("Reporte de libros");
            documento.addAuthor("Salvador Antonio Juarez Cruz");

            PdfPTable tabla = new PdfPTable(7);
            tabla.addCell("Nombre");
            tabla.addCell("Estado");
            tabla.addCell("Año");
            tabla.addCell("Autor");
            tabla.addCell("Editorial");
            tabla.addCell("ID");
            tabla.addCell("Mantenimiento");

            try {
                Connection cn = DriverManager.getConnection("jdbc:mariadb://localhost:3305/Librerias", "root", "1234");
                PreparedStatement pst = cn.prepareStatement("select * from Libreria");

                ResultSet rs = pst.executeQuery();

                if(rs.next()){

                    do {
                        tabla.addCell(rs.getString(1));
                        tabla.addCell(rs.getString(2));
                        tabla.addCell(rs.getString(3));
                        tabla.addCell(rs.getString(4));
                        tabla.addCell(rs.getString(5));
                        tabla.addCell(rs.getString(6));
                        tabla.addCell(rs.getString(7));
                    } while (rs.next());
                    documento.add(tabla);
                }

            } catch (DocumentException | SQLException e) {
                e.printStackTrace();
            }
            documento.close();
            JOptionPane.showMessageDialog(null, "Reporte creado.");
        } catch (DocumentException | HeadlessException | FileNotFoundException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        try {
            Connection cn = DriverManager.getConnection("jdbc:mariadb://localhost:3305/Librerias", "root", "1234");
            PreparedStatement pst = cn.prepareStatement("select * from Libreria where ID = ?");
            pst.setString(1, BuscaId.getText().trim());

            ResultSet rs = pst.executeQuery();

            if (rs.next()) {
                Nombre.setText(rs.getString("Nombre"));
                Año.setText(rs.getString("Año"));
                Estado.setText(rs.getString("Estado"));
                Autor.setText(rs.getString("Autor"));
                Editorial.setText(rs.getString("Editorial"));
                Id.setText(rs.getString("Id"));
                Mantenimiento.setText(rs.getString("Mantenimiento"));
            } else {
                JOptionPane.showMessageDialog(null, "Libro no registrado.");
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazBiblio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazBiblio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazBiblio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazBiblio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazBiblio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Autor;
    private javax.swing.JTextField Año;
    private javax.swing.JTextField BuscaId;
    private javax.swing.JTextField Editorial;
    private javax.swing.JTextField Estado;
    private javax.swing.JTextField Id;
    private javax.swing.JTextField Mantenimiento;
    private javax.swing.JTextField Nombre;
    private javax.swing.JLabel fondo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel label_status;
    // End of variables declaration//GEN-END:variables
}
